// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/download.dart';
import 'api/image_utils.dart';
import 'api/zip_utils.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'third_party/pixiv_rs/api.dart';
import 'third_party/pixiv_rs/auth.dart';
import 'third_party/pixiv_rs/enums.dart';
import 'third_party/pixiv_rs/error.dart';
import 'third_party/pixiv_rs/models.dart';
import 'third_party/pixiv_rs/responses.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_GifErrorPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGifErrorPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PixivApiPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivApiPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PixivAuthPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivAuthPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_UnzipErrorPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUnzipErrorPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  GifError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGifError(
    dynamic raw,
  );

  @protected
  PixivApi
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivApi(
    dynamic raw,
  );

  @protected
  PixivAuth
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivAuth(
    dynamic raw,
  );

  @protected
  UnzipError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUnzipError(
    dynamic raw,
  );

  @protected
  PixivApi
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivApi(
    dynamic raw,
  );

  @protected
  PixivAuth
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivAuth(
    dynamic raw,
  );

  @protected
  int dco_decode_CastedPrimitive_i_64(dynamic raw);

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw);

  @protected
  GifError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGifError(
    dynamic raw,
  );

  @protected
  PixivApi
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivApi(
    dynamic raw,
  );

  @protected
  PixivAuth
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivAuth(
    dynamic raw,
  );

  @protected
  UnzipError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUnzipError(
    dynamic raw,
  );

  @protected
  RustStreamSink<FrbDownloadBytesEvent>
  dco_decode_StreamSink_frb_download_bytes_event_Sse(dynamic raw);

  @protected
  RustStreamSink<FrbDownloadFileEvent>
  dco_decode_StreamSink_frb_download_file_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  PixivEnumParam dco_decode_TraitDef_PixivEnumParam(dynamic raw);

  @protected
  BookmarkAddOptions dco_decode_bookmark_add_options(dynamic raw);

  @protected
  BookmarkTag dco_decode_bookmark_tag(dynamic raw);

  @protected
  BookmarkTagOptions dco_decode_bookmark_tag_options(dynamic raw);

  @protected
  BookmarkTagPageResult dco_decode_bookmark_tag_page_result(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BookmarkAddOptions dco_decode_box_autoadd_bookmark_add_options(dynamic raw);

  @protected
  BookmarkTagOptions dco_decode_box_autoadd_bookmark_tag_options(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  CommentAddOptions dco_decode_box_autoadd_comment_add_options(dynamic raw);

  @protected
  Illust dco_decode_box_autoadd_illust(dynamic raw);

  @protected
  NovelNavigationInfo dco_decode_box_autoadd_novel_navigation_info(dynamic raw);

  @protected
  NovelNavigationItem dco_decode_box_autoadd_novel_navigation_item(dynamic raw);

  @protected
  PixivApiConfig dco_decode_box_autoadd_pixiv_api_config(dynamic raw);

  @protected
  PixivAuthConfig dco_decode_box_autoadd_pixiv_auth_config(dynamic raw);

  @protected
  Restrict dco_decode_box_autoadd_restrict(dynamic raw);

  @protected
  SearchOptions dco_decode_box_autoadd_search_options(dynamic raw);

  @protected
  Stamp dco_decode_box_autoadd_stamp(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  UserAccountResult dco_decode_box_autoadd_user_account_result(dynamic raw);

  @protected
  Comment dco_decode_comment(dynamic raw);

  @protected
  CommentAddOptions dco_decode_comment_add_options(dynamic raw);

  @protected
  CommentAddResult dco_decode_comment_add_result(dynamic raw);

  @protected
  CommentPageResult dco_decode_comment_page_result(dynamic raw);

  @protected
  Frame dco_decode_frame(dynamic raw);

  @protected
  FrbDownloadBytesEvent dco_decode_frb_download_bytes_event(dynamic raw);

  @protected
  FrbDownloadFileEvent dco_decode_frb_download_file_event(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Illust dco_decode_illust(dynamic raw);

  @protected
  IllustDetailResult dco_decode_illust_detail_result(dynamic raw);

  @protected
  IllustPageResult dco_decode_illust_page_result(dynamic raw);

  @protected
  IllustRankingMode dco_decode_illust_ranking_mode(dynamic raw);

  @protected
  IllustType dco_decode_illust_type(dynamic raw);

  @protected
  ImageUrls dco_decode_image_urls(dynamic raw);

  @protected
  ImageUtils dco_decode_image_utils(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BookmarkTag> dco_decode_list_bookmark_tag(dynamic raw);

  @protected
  List<Comment> dco_decode_list_comment(dynamic raw);

  @protected
  List<Frame> dco_decode_list_frame(dynamic raw);

  @protected
  List<Illust> dco_decode_list_illust(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<MetaPage> dco_decode_list_meta_page(dynamic raw);

  @protected
  List<Novel> dco_decode_list_novel(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_i_32_loose(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Tag> dco_decode_list_tag(dynamic raw);

  @protected
  List<TrendTag> dco_decode_list_trend_tag(dynamic raw);

  @protected
  List<UserPreview> dco_decode_list_user_preview(dynamic raw);

  @protected
  List<WebviewNovelImage> dco_decode_list_webview_novel_image(dynamic raw);

  @protected
  LocalUser dco_decode_local_user(dynamic raw);

  @protected
  LocalUserProfileImageUrls dco_decode_local_user_profile_image_urls(
    dynamic raw,
  );

  @protected
  MangaRankingMode dco_decode_manga_ranking_mode(dynamic raw);

  @protected
  MetaPage dco_decode_meta_page(dynamic raw);

  @protected
  MetaSinglePage dco_decode_meta_single_page(dynamic raw);

  @protected
  Novel dco_decode_novel(dynamic raw);

  @protected
  NovelDetailResult dco_decode_novel_detail_result(dynamic raw);

  @protected
  NovelNavigationInfo dco_decode_novel_navigation_info(dynamic raw);

  @protected
  NovelNavigationItem dco_decode_novel_navigation_item(dynamic raw);

  @protected
  NovelPageResult dco_decode_novel_page_result(dynamic raw);

  @protected
  NovelRankingMode dco_decode_novel_ranking_mode(dynamic raw);

  @protected
  NovelRating dco_decode_novel_rating(dynamic raw);

  @protected
  int? dco_decode_opt_CastedPrimitive_u_64(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  NovelNavigationInfo? dco_decode_opt_box_autoadd_novel_navigation_info(
    dynamic raw,
  );

  @protected
  NovelNavigationItem? dco_decode_opt_box_autoadd_novel_navigation_item(
    dynamic raw,
  );

  @protected
  Restrict? dco_decode_opt_box_autoadd_restrict(dynamic raw);

  @protected
  Stamp? dco_decode_opt_box_autoadd_stamp(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  UserAccountResult? dco_decode_opt_box_autoadd_user_account_result(
    dynamic raw,
  );

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  PixivApiConfig dco_decode_pixiv_api_config(dynamic raw);

  @protected
  PixivAuthConfig dco_decode_pixiv_auth_config(dynamic raw);

  @protected
  PixivError dco_decode_pixiv_error(dynamic raw);

  @protected
  PixivErrorKind dco_decode_pixiv_error_kind(dynamic raw);

  @protected
  ProfileImageUrls dco_decode_profile_image_urls(dynamic raw);

  @protected
  Restrict dco_decode_restrict(dynamic raw);

  @protected
  SearchAutocompleteResult dco_decode_search_autocomplete_result(dynamic raw);

  @protected
  SearchIllustPageResult dco_decode_search_illust_page_result(dynamic raw);

  @protected
  SearchNovelPageResult dco_decode_search_novel_page_result(dynamic raw);

  @protected
  SearchOptions dco_decode_search_options(dynamic raw);

  @protected
  SearchSort dco_decode_search_sort(dynamic raw);

  @protected
  SearchTarget dco_decode_search_target(dynamic raw);

  @protected
  Series dco_decode_series(dynamic raw);

  @protected
  Stamp dco_decode_stamp(dynamic raw);

  @protected
  Tag dco_decode_tag(dynamic raw);

  @protected
  TrendTag dco_decode_trend_tag(dynamic raw);

  @protected
  TrendingTagListResult dco_decode_trending_tag_list_result(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UgoiraMetadataContent dco_decode_ugoira_metadata_content(dynamic raw);

  @protected
  UgoiraMetadataResult dco_decode_ugoira_metadata_result(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  User dco_decode_user(dynamic raw);

  @protected
  UserAccountResult dco_decode_user_account_result(dynamic raw);

  @protected
  UserDetailResult dco_decode_user_detail_result(dynamic raw);

  @protected
  UserInfo dco_decode_user_info(dynamic raw);

  @protected
  UserPageResult dco_decode_user_page_result(dynamic raw);

  @protected
  UserPreview dco_decode_user_preview(dynamic raw);

  @protected
  UserProfile dco_decode_user_profile(dynamic raw);

  @protected
  UserProfilePublicity dco_decode_user_profile_publicity(dynamic raw);

  @protected
  UserWorkspace dco_decode_user_workspace(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WebviewNovel dco_decode_webview_novel(dynamic raw);

  @protected
  WebviewNovelImage dco_decode_webview_novel_image(dynamic raw);

  @protected
  WebviewNovelImageUrls dco_decode_webview_novel_image_urls(dynamic raw);

  @protected
  WorkType dco_decode_work_type(dynamic raw);

  @protected
  ZipUrls dco_decode_zip_urls(dynamic raw);

  @protected
  ZipUtils dco_decode_zip_utils(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  GifError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGifError(
    SseDeserializer deserializer,
  );

  @protected
  PixivApi
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivApi(
    SseDeserializer deserializer,
  );

  @protected
  PixivAuth
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivAuth(
    SseDeserializer deserializer,
  );

  @protected
  UnzipError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUnzipError(
    SseDeserializer deserializer,
  );

  @protected
  PixivApi
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivApi(
    SseDeserializer deserializer,
  );

  @protected
  PixivAuth
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivAuth(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_CastedPrimitive_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  GifError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGifError(
    SseDeserializer deserializer,
  );

  @protected
  PixivApi
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivApi(
    SseDeserializer deserializer,
  );

  @protected
  PixivAuth
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivAuth(
    SseDeserializer deserializer,
  );

  @protected
  UnzipError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUnzipError(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<FrbDownloadBytesEvent>
  sse_decode_StreamSink_frb_download_bytes_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<FrbDownloadFileEvent>
  sse_decode_StreamSink_frb_download_file_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BookmarkAddOptions sse_decode_bookmark_add_options(
    SseDeserializer deserializer,
  );

  @protected
  BookmarkTag sse_decode_bookmark_tag(SseDeserializer deserializer);

  @protected
  BookmarkTagOptions sse_decode_bookmark_tag_options(
    SseDeserializer deserializer,
  );

  @protected
  BookmarkTagPageResult sse_decode_bookmark_tag_page_result(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BookmarkAddOptions sse_decode_box_autoadd_bookmark_add_options(
    SseDeserializer deserializer,
  );

  @protected
  BookmarkTagOptions sse_decode_box_autoadd_bookmark_tag_options(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CommentAddOptions sse_decode_box_autoadd_comment_add_options(
    SseDeserializer deserializer,
  );

  @protected
  Illust sse_decode_box_autoadd_illust(SseDeserializer deserializer);

  @protected
  NovelNavigationInfo sse_decode_box_autoadd_novel_navigation_info(
    SseDeserializer deserializer,
  );

  @protected
  NovelNavigationItem sse_decode_box_autoadd_novel_navigation_item(
    SseDeserializer deserializer,
  );

  @protected
  PixivApiConfig sse_decode_box_autoadd_pixiv_api_config(
    SseDeserializer deserializer,
  );

  @protected
  PixivAuthConfig sse_decode_box_autoadd_pixiv_auth_config(
    SseDeserializer deserializer,
  );

  @protected
  Restrict sse_decode_box_autoadd_restrict(SseDeserializer deserializer);

  @protected
  SearchOptions sse_decode_box_autoadd_search_options(
    SseDeserializer deserializer,
  );

  @protected
  Stamp sse_decode_box_autoadd_stamp(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  UserAccountResult sse_decode_box_autoadd_user_account_result(
    SseDeserializer deserializer,
  );

  @protected
  Comment sse_decode_comment(SseDeserializer deserializer);

  @protected
  CommentAddOptions sse_decode_comment_add_options(
    SseDeserializer deserializer,
  );

  @protected
  CommentAddResult sse_decode_comment_add_result(SseDeserializer deserializer);

  @protected
  CommentPageResult sse_decode_comment_page_result(
    SseDeserializer deserializer,
  );

  @protected
  Frame sse_decode_frame(SseDeserializer deserializer);

  @protected
  FrbDownloadBytesEvent sse_decode_frb_download_bytes_event(
    SseDeserializer deserializer,
  );

  @protected
  FrbDownloadFileEvent sse_decode_frb_download_file_event(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Illust sse_decode_illust(SseDeserializer deserializer);

  @protected
  IllustDetailResult sse_decode_illust_detail_result(
    SseDeserializer deserializer,
  );

  @protected
  IllustPageResult sse_decode_illust_page_result(SseDeserializer deserializer);

  @protected
  IllustRankingMode sse_decode_illust_ranking_mode(
    SseDeserializer deserializer,
  );

  @protected
  IllustType sse_decode_illust_type(SseDeserializer deserializer);

  @protected
  ImageUrls sse_decode_image_urls(SseDeserializer deserializer);

  @protected
  ImageUtils sse_decode_image_utils(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BookmarkTag> sse_decode_list_bookmark_tag(SseDeserializer deserializer);

  @protected
  List<Comment> sse_decode_list_comment(SseDeserializer deserializer);

  @protected
  List<Frame> sse_decode_list_frame(SseDeserializer deserializer);

  @protected
  List<Illust> sse_decode_list_illust(SseDeserializer deserializer);

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<MetaPage> sse_decode_list_meta_page(SseDeserializer deserializer);

  @protected
  List<Novel> sse_decode_list_novel(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_i_32_loose(SseDeserializer deserializer);

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Tag> sse_decode_list_tag(SseDeserializer deserializer);

  @protected
  List<TrendTag> sse_decode_list_trend_tag(SseDeserializer deserializer);

  @protected
  List<UserPreview> sse_decode_list_user_preview(SseDeserializer deserializer);

  @protected
  List<WebviewNovelImage> sse_decode_list_webview_novel_image(
    SseDeserializer deserializer,
  );

  @protected
  LocalUser sse_decode_local_user(SseDeserializer deserializer);

  @protected
  LocalUserProfileImageUrls sse_decode_local_user_profile_image_urls(
    SseDeserializer deserializer,
  );

  @protected
  MangaRankingMode sse_decode_manga_ranking_mode(SseDeserializer deserializer);

  @protected
  MetaPage sse_decode_meta_page(SseDeserializer deserializer);

  @protected
  MetaSinglePage sse_decode_meta_single_page(SseDeserializer deserializer);

  @protected
  Novel sse_decode_novel(SseDeserializer deserializer);

  @protected
  NovelDetailResult sse_decode_novel_detail_result(
    SseDeserializer deserializer,
  );

  @protected
  NovelNavigationInfo sse_decode_novel_navigation_info(
    SseDeserializer deserializer,
  );

  @protected
  NovelNavigationItem sse_decode_novel_navigation_item(
    SseDeserializer deserializer,
  );

  @protected
  NovelPageResult sse_decode_novel_page_result(SseDeserializer deserializer);

  @protected
  NovelRankingMode sse_decode_novel_ranking_mode(SseDeserializer deserializer);

  @protected
  NovelRating sse_decode_novel_rating(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_CastedPrimitive_u_64(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  NovelNavigationInfo? sse_decode_opt_box_autoadd_novel_navigation_info(
    SseDeserializer deserializer,
  );

  @protected
  NovelNavigationItem? sse_decode_opt_box_autoadd_novel_navigation_item(
    SseDeserializer deserializer,
  );

  @protected
  Restrict? sse_decode_opt_box_autoadd_restrict(SseDeserializer deserializer);

  @protected
  Stamp? sse_decode_opt_box_autoadd_stamp(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  UserAccountResult? sse_decode_opt_box_autoadd_user_account_result(
    SseDeserializer deserializer,
  );

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  PixivApiConfig sse_decode_pixiv_api_config(SseDeserializer deserializer);

  @protected
  PixivAuthConfig sse_decode_pixiv_auth_config(SseDeserializer deserializer);

  @protected
  PixivError sse_decode_pixiv_error(SseDeserializer deserializer);

  @protected
  PixivErrorKind sse_decode_pixiv_error_kind(SseDeserializer deserializer);

  @protected
  ProfileImageUrls sse_decode_profile_image_urls(SseDeserializer deserializer);

  @protected
  Restrict sse_decode_restrict(SseDeserializer deserializer);

  @protected
  SearchAutocompleteResult sse_decode_search_autocomplete_result(
    SseDeserializer deserializer,
  );

  @protected
  SearchIllustPageResult sse_decode_search_illust_page_result(
    SseDeserializer deserializer,
  );

  @protected
  SearchNovelPageResult sse_decode_search_novel_page_result(
    SseDeserializer deserializer,
  );

  @protected
  SearchOptions sse_decode_search_options(SseDeserializer deserializer);

  @protected
  SearchSort sse_decode_search_sort(SseDeserializer deserializer);

  @protected
  SearchTarget sse_decode_search_target(SseDeserializer deserializer);

  @protected
  Series sse_decode_series(SseDeserializer deserializer);

  @protected
  Stamp sse_decode_stamp(SseDeserializer deserializer);

  @protected
  Tag sse_decode_tag(SseDeserializer deserializer);

  @protected
  TrendTag sse_decode_trend_tag(SseDeserializer deserializer);

  @protected
  TrendingTagListResult sse_decode_trending_tag_list_result(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UgoiraMetadataContent sse_decode_ugoira_metadata_content(
    SseDeserializer deserializer,
  );

  @protected
  UgoiraMetadataResult sse_decode_ugoira_metadata_result(
    SseDeserializer deserializer,
  );

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  User sse_decode_user(SseDeserializer deserializer);

  @protected
  UserAccountResult sse_decode_user_account_result(
    SseDeserializer deserializer,
  );

  @protected
  UserDetailResult sse_decode_user_detail_result(SseDeserializer deserializer);

  @protected
  UserInfo sse_decode_user_info(SseDeserializer deserializer);

  @protected
  UserPageResult sse_decode_user_page_result(SseDeserializer deserializer);

  @protected
  UserPreview sse_decode_user_preview(SseDeserializer deserializer);

  @protected
  UserProfile sse_decode_user_profile(SseDeserializer deserializer);

  @protected
  UserProfilePublicity sse_decode_user_profile_publicity(
    SseDeserializer deserializer,
  );

  @protected
  UserWorkspace sse_decode_user_workspace(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WebviewNovel sse_decode_webview_novel(SseDeserializer deserializer);

  @protected
  WebviewNovelImage sse_decode_webview_novel_image(
    SseDeserializer deserializer,
  );

  @protected
  WebviewNovelImageUrls sse_decode_webview_novel_image_urls(
    SseDeserializer deserializer,
  );

  @protected
  WorkType sse_decode_work_type(SseDeserializer deserializer);

  @protected
  ZipUrls sse_decode_zip_urls(SseDeserializer deserializer);

  @protected
  ZipUtils sse_decode_zip_utils(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGifError(
    GifError self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivApi(
    PixivApi self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivAuth(
    PixivAuth self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUnzipError(
    UnzipError self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivApi(
    PixivApi self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivAuth(
    PixivAuth self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_CastedPrimitive_i_64(int self, SseSerializer serializer);

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer);

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGifError(
    GifError self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivApi(
    PixivApi self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivAuth(
    PixivAuth self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUnzipError(
    UnzipError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_frb_download_bytes_event_Sse(
    RustStreamSink<FrbDownloadBytesEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_frb_download_file_event_Sse(
    RustStreamSink<FrbDownloadFileEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bookmark_add_options(
    BookmarkAddOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bookmark_tag(BookmarkTag self, SseSerializer serializer);

  @protected
  void sse_encode_bookmark_tag_options(
    BookmarkTagOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bookmark_tag_page_result(
    BookmarkTagPageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bookmark_add_options(
    BookmarkAddOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bookmark_tag_options(
    BookmarkTagOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_comment_add_options(
    CommentAddOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_illust(Illust self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_novel_navigation_info(
    NovelNavigationInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_novel_navigation_item(
    NovelNavigationItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pixiv_api_config(
    PixivApiConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pixiv_auth_config(
    PixivAuthConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_restrict(Restrict self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_search_options(
    SearchOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_stamp(Stamp self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_user_account_result(
    UserAccountResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_comment(Comment self, SseSerializer serializer);

  @protected
  void sse_encode_comment_add_options(
    CommentAddOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_comment_add_result(
    CommentAddResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_comment_page_result(
    CommentPageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frame(Frame self, SseSerializer serializer);

  @protected
  void sse_encode_frb_download_bytes_event(
    FrbDownloadBytesEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_frb_download_file_event(
    FrbDownloadFileEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_illust(Illust self, SseSerializer serializer);

  @protected
  void sse_encode_illust_detail_result(
    IllustDetailResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_illust_page_result(
    IllustPageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_illust_ranking_mode(
    IllustRankingMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_illust_type(IllustType self, SseSerializer serializer);

  @protected
  void sse_encode_image_urls(ImageUrls self, SseSerializer serializer);

  @protected
  void sse_encode_image_utils(ImageUtils self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bookmark_tag(
    List<BookmarkTag> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_comment(List<Comment> self, SseSerializer serializer);

  @protected
  void sse_encode_list_frame(List<Frame> self, SseSerializer serializer);

  @protected
  void sse_encode_list_illust(List<Illust> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_meta_page(List<MetaPage> self, SseSerializer serializer);

  @protected
  void sse_encode_list_novel(List<Novel> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_i_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tag(List<Tag> self, SseSerializer serializer);

  @protected
  void sse_encode_list_trend_tag(List<TrendTag> self, SseSerializer serializer);

  @protected
  void sse_encode_list_user_preview(
    List<UserPreview> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_webview_novel_image(
    List<WebviewNovelImage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_local_user(LocalUser self, SseSerializer serializer);

  @protected
  void sse_encode_local_user_profile_image_urls(
    LocalUserProfileImageUrls self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_manga_ranking_mode(
    MangaRankingMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_meta_page(MetaPage self, SseSerializer serializer);

  @protected
  void sse_encode_meta_single_page(
    MetaSinglePage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_novel(Novel self, SseSerializer serializer);

  @protected
  void sse_encode_novel_detail_result(
    NovelDetailResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_novel_navigation_info(
    NovelNavigationInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_novel_navigation_item(
    NovelNavigationItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_novel_page_result(
    NovelPageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_novel_ranking_mode(
    NovelRankingMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_novel_rating(NovelRating self, SseSerializer serializer);

  @protected
  void sse_encode_opt_CastedPrimitive_u_64(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_novel_navigation_info(
    NovelNavigationInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_novel_navigation_item(
    NovelNavigationItem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_restrict(
    Restrict? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_stamp(Stamp? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_user_account_result(
    UserAccountResult? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_pixiv_api_config(
    PixivApiConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pixiv_auth_config(
    PixivAuthConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pixiv_error(PixivError self, SseSerializer serializer);

  @protected
  void sse_encode_pixiv_error_kind(
    PixivErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_profile_image_urls(
    ProfileImageUrls self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_restrict(Restrict self, SseSerializer serializer);

  @protected
  void sse_encode_search_autocomplete_result(
    SearchAutocompleteResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_illust_page_result(
    SearchIllustPageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_novel_page_result(
    SearchNovelPageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_options(SearchOptions self, SseSerializer serializer);

  @protected
  void sse_encode_search_sort(SearchSort self, SseSerializer serializer);

  @protected
  void sse_encode_search_target(SearchTarget self, SseSerializer serializer);

  @protected
  void sse_encode_series(Series self, SseSerializer serializer);

  @protected
  void sse_encode_stamp(Stamp self, SseSerializer serializer);

  @protected
  void sse_encode_tag(Tag self, SseSerializer serializer);

  @protected
  void sse_encode_trend_tag(TrendTag self, SseSerializer serializer);

  @protected
  void sse_encode_trending_tag_list_result(
    TrendingTagListResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_ugoira_metadata_content(
    UgoiraMetadataContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ugoira_metadata_result(
    UgoiraMetadataResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user(User self, SseSerializer serializer);

  @protected
  void sse_encode_user_account_result(
    UserAccountResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_user_detail_result(
    UserDetailResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_user_info(UserInfo self, SseSerializer serializer);

  @protected
  void sse_encode_user_page_result(
    UserPageResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_user_preview(UserPreview self, SseSerializer serializer);

  @protected
  void sse_encode_user_profile(UserProfile self, SseSerializer serializer);

  @protected
  void sse_encode_user_profile_publicity(
    UserProfilePublicity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_user_workspace(UserWorkspace self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_webview_novel(WebviewNovel self, SseSerializer serializer);

  @protected
  void sse_encode_webview_novel_image(
    WebviewNovelImage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_webview_novel_image_urls(
    WebviewNovelImageUrls self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_work_type(WorkType self, SseSerializer serializer);

  @protected
  void sse_encode_zip_urls(ZipUrls self, SseSerializer serializer);

  @protected
  void sse_encode_zip_utils(ZipUtils self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGifError(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGifError(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGifErrorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_freepiv_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGifError',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGifError =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGifErrorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGifError(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGifError(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGifErrorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_freepiv_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGifError',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGifError =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerGifErrorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivApi(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivApi(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivApiPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_freepiv_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivApi',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivApi =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivApiPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivApi(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivApi(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivApiPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_freepiv_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivApi',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivApi =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivApiPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivAuth(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivAuth(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivAuthPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_freepiv_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivAuth',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivAuth =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivAuthPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivAuth(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivAuth(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivAuthPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_freepiv_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivAuth',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivAuth =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPixivAuthPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUnzipError(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUnzipError(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUnzipErrorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_freepiv_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUnzipError',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUnzipError =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUnzipErrorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUnzipError(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUnzipError(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUnzipErrorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_freepiv_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUnzipError',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUnzipError =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerUnzipErrorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
