[package]
name = "core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.13.0"
pixiv_rs = { git = "https://github.com/normalllll/pixiv_rs.git", branch = "main" }
futures-util = "0.3.32"
reqwest = { version = "0.13.4", default-features = false, features = ["rustls", "stream", "http2", "socks", "system-proxy"] }
tokio = { version = "1", features = ["fs", "io-util"] }
md-5 = "0.10.6"
sha2 = "0.10.9"
gif = { version = "0.14.2" }
image = { version = "0.25.10", default-features = false, features = ["gif", "jpeg", "png", "webp"] }
zip = { version = "9.0.0-pre2" }
thiserror = "2.0.18"
[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[target.'cfg(target_os = "windows")'.dependencies]
wry = "=0.57.0"
tao = "=0.37.0"
muda = "=0.19.3"
windows = { version = "=0.62.2", features = ["Win32_Foundation", "Win32_System_Com", "Win32_UI_WindowsAndMessaging"] }
webview2-com = "=0.39.1"
