// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'download.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `emit_progress`, `finish`, `new`, `non_empty`, `parse_headers`, `progress_value`, `remove_invalid_file`, `update`, `validate_content_type`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `StreamingChecksum`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Stream<FrbDownloadBytesEvent> downloadToMemory({
  required String url,
  String? proxy,
}) => RustLib.instance.api.crateApiDownloadDownloadToMemory(
  url: url,
  proxy: proxy,
);

Stream<FrbDownloadFileEvent> downloadToFile({
  required String url,
  required String path,
  required Map<String, String> headers,
  String? proxyUrl,
  String? connectHost,
  String? hostHeader,
  required bool disableTlsSni,
  required bool allowInvalidCertificates,
  required int connectTimeoutSeconds,
  required int receiveTimeoutSeconds,
  int? expectedBytes,
  required List<String> allowedContentTypes,
  String? checksumAlgorithm,
  String? checksumValue,
}) => RustLib.instance.api.crateApiDownloadDownloadToFile(
  url: url,
  path: path,
  headers: headers,
  proxyUrl: proxyUrl,
  connectHost: connectHost,
  hostHeader: hostHeader,
  disableTlsSni: disableTlsSni,
  allowInvalidCertificates: allowInvalidCertificates,
  connectTimeoutSeconds: connectTimeoutSeconds,
  receiveTimeoutSeconds: receiveTimeoutSeconds,
  expectedBytes: expectedBytes,
  allowedContentTypes: allowedContentTypes,
  checksumAlgorithm: checksumAlgorithm,
  checksumValue: checksumValue,
);

@freezed
sealed class FrbDownloadBytesEvent with _$FrbDownloadBytesEvent {
  const FrbDownloadBytesEvent._();

  const factory FrbDownloadBytesEvent.progress({
    required int received,
    required int total,
  }) = FrbDownloadBytesEvent_Progress;
  const factory FrbDownloadBytesEvent.done({required Uint8List bytes}) =
      FrbDownloadBytesEvent_Done;
}

@freezed
sealed class FrbDownloadFileEvent with _$FrbDownloadFileEvent {
  const FrbDownloadFileEvent._();

  const factory FrbDownloadFileEvent.progress({
    required int received,
    required int total,
  }) = FrbDownloadFileEvent_Progress;
  const factory FrbDownloadFileEvent.done({required String path}) =
      FrbDownloadFileEvent_Done;
}
