// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'download.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Stream<FrbDownloadBytesEvent> downloadToMemory({required String url}) =>
    RustLib.instance.api.crateApiDownloadDownloadToMemory(url: url);

Stream<FrbDownloadFileEvent> downloadToFile({
  required String url,
  required String path,
}) => RustLib.instance.api.crateApiDownloadDownloadToFile(url: url, path: path);

@freezed
sealed class FrbDownloadBytesEvent with _$FrbDownloadBytesEvent {
  const FrbDownloadBytesEvent._();

  const factory FrbDownloadBytesEvent.progress({
    required int received,
    required int total,
  }) = FrbDownloadBytesEvent_Progress;
  const factory FrbDownloadBytesEvent.done({required Uint8List bytes}) =
      FrbDownloadBytesEvent_Done;
}

@freezed
sealed class FrbDownloadFileEvent with _$FrbDownloadFileEvent {
  const FrbDownloadFileEvent._();

  const factory FrbDownloadFileEvent.progress({
    required int received,
    required int total,
  }) = FrbDownloadFileEvent_Progress;
  const factory FrbDownloadFileEvent.done({required String path}) =
      FrbDownloadFileEvent_Done;
}
