// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `fmt`

Future<bool> fanboxBrowserAvailable() =>
    RustLib.instance.api.crateApiFanboxLoginFanboxBrowserAvailable();

Future<void> clearFanboxBrowser({required String supportDirectory}) => RustLib
    .instance
    .api
    .crateApiFanboxLoginClearFanboxBrowser(supportDirectory: supportDirectory);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FanboxBrowserLogin>>
abstract class FanboxBrowserLogin implements RustOpaqueInterface {
  void cancel();

  factory FanboxBrowserLogin() =>
      RustLib.instance.api.crateApiFanboxLoginFanboxBrowserLoginNew();

  Future<String?> run({
    required String supportDirectory,
    String? proxy,
    required String language,
    required String title,
    required String checkLabel,
    required String cancelLabel,
    required String failedLabel,
  });
}

enum FanboxBrowserFailure {
  runtimeMissing,
  unavailable,
  busy,
  proxyUnsupported,
  cleanupFailed,
  timedOut,
}
