// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.5.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `from`, `source`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GifError>>
abstract class GifError implements RustOpaqueInterface {}

class ImageUtils {
  const ImageUtils();

  /// Combines multiple images into a GIF.
  /// images: The raw bytes of each image, such as png/jpg/webp, etc.
  /// delays: The delay per frame, in milliseconds.
  /// Returns: GIF file bytes.
  static Future<Uint8List> imagesToGif({
    required List<Uint8List> images,
    required List<int> delays,
  }) => RustLib.instance.api.crateApiImageUtilsImageUtilsImagesToGif(
    images: images,
    delays: delays,
  );

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageUtils && runtimeType == other.runtimeType;
}
