// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<MediaChunk> streamMedia({
  required String url,
  String? proxy,
  required Map<String, String> headers,
}) => RustLib.instance.api.crateApiMediaStreamMedia(
  url: url,
  proxy: proxy,
  headers: headers,
);

class MediaChunk {
  final Uint8List bytes;
  final int received;
  final int? total;

  const MediaChunk({required this.bytes, required this.received, this.total});

  @override
  int get hashCode => bytes.hashCode ^ received.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaChunk &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          received == other.received &&
          total == other.total;
}
