// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `command_output`, `get_platform_system_proxy`, `gsettings_proxy_url`, `normalize_http_proxy_url`, `proxy_url_from_environment`, `proxy_url_from_gsettings`, `proxy_url_from_host_port`, `unquote_gsettings_value`

Future<String?> getSystemProxy() =>
    RustLib.instance.api.crateApiProxyGetSystemProxy();
