// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `command_output`, `get_platform_system_proxy`, `normalize_http_proxy_url`, `proxy_url_from_windows_proxy_server`, `query_windows_internet_setting`, `windows_proxy_enabled`

Future<String?> getSystemProxy() =>
    RustLib.instance.api.crateApiProxyGetSystemProxy();
