// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.4.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `source`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UnzipError>>
abstract class UnzipError implements RustOpaqueInterface {}

class ZipUtils {
  const ZipUtils();

  /// Unzips the ZIP archive and returns the bytes of all regular files within.
  /// bytes: The original bytes of the zip file.
  /// Returns: The bytes of each file within the zip archive.
  /// Directories are skipped; filenames, paths, and passwords are not processed separately.
  static Future<List<Uint8List>> unzipFiles({required List<int> bytes}) =>
      RustLib.instance.api.crateApiZipUtilsZipUtilsUnzipFiles(bytes: bytes);

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZipUtils && runtimeType == other.runtimeType;
}
